package commons;

public enum Eventos {
	INICIO_PARTIDA,
	NUEVA_RONDA,
	COMIENZA_FICHA_ALTA,
	JUGADOR_TIRAR_DOBLE,	
	MOSTRAR_FICHAS_JUGADOR,	
	MOSTRAR_FICHAS_MESA,
	MOSTRAR_TURNO,	
	JUGADOR_ELEGIR_FICHA,
	AMBOS_EXTREMOS,
	JUGADOR_JUNTAR_POZO,
	MOSTRAR_POZO,
	JUNTO_PUEDE_TIRAR,
	JUNTO_NO_PUEDE_TIRAR,
	DOMINO,
	PASA,
	CIERRE,
	CONFIRMAR_NUEVA_RONDA,
	FIN_PARTIDA,
}

