package vista;

public enum Estados {
	VENTANA_INGRESO,
	VISTA_INICIADA,
	ESPERANDO_ELECCION_PONER_DOBLE,
	ESPERANDO_ELECCION_FICHA,
	ESPERANDO_ELECCION_EXTREMO,
	ESPERANDO_ELECCION_JUNTAR_POZO,
	ESPERANDO_ELECCION_PONER_FICHA_JUNTADA,
	ESPERANDO_ELECCION_PASAR,
	ESPERANDO_ELECCION_NUEVA_RONDA
	
}
